### PR TITLE
Joachim's memory fixes

### PR DESCRIPTION
**Pull request by jwiegley**

### CODE REVIEW

**Comment by nomeata** [comment]
Ah, you already created a PR. was just about to create a draft…

So far it is mostly one bug PR, and some things need some cleanup before merging. Do you want me to split it into separate PRs or is that not so important?

One observation I made is that using the interpreter with a monad stack on top of `ST s` (or `IO`) (in may case, with a `StateT` on top) slows it down by a factor of 6-7.

I would recommend make the code more monomorphic and
 * copy `Wasm.Exec.Eval` to `Wasm.Exec.Eval.ST`, and replace the `m` everywhere with simply `ST s`
 * make `Wasm.Exec.Eval` provide the same interface, but with `IO`, by wrapping the above interface (remember `ST RealWorld = IO`).

If people need “extra functionality” beyond `ST s` or `IO` in (presumably) their host functions, they need to use out-of-band mechanisms (`IORef`,  exceptions).

What do you think, @jwiegley? Reasonable, or is the flexibility of a general `MonadRef m` too important?

I also changed how the test suite finds the wasm specs.

**Comment by jwiegley** [comment]
I don't think `MonadRef m` is terribly important.

Is this ready to be merged in?

**Comment by nomeata** [comment]
If you are fine with making it monad-monomorphic (to `ST s`), then maybe I’ll do that first.

**Comment by jwiegley** [comment]
Yes, I'm quite fine with that.

**Comment by nomeata** [comment]
Decided against making everything monomorphic, it was too much work. Instead, the module documentation states that you should use `IO` or `ST s` if you want performance.

Functionally this can go in now.

Did you use a code formatter here that I should run over my code? (There is no `README`, and the `default.nix` doesn't check anything, so I am not sure)

Also it seems you have a `.travis.yaml` but no travis is set up.

**Comment by jwiegley** [comment]
I think I was using brittany, but I don't have it setup anymore.

**Pull request merged**
